### ISSUE TITLE
AnnotSV doesn't add the sample IDs causing variantconvert to fail

### ISSUE THREAD

**Issue by nvnieuwk** [lgmgeo/AnnotSV#180]
Hi, 

I've encountered a variantconvert error when running with the `-vcf 1` option. Which looks like this:
```
python3 /usr/local/share/python3/variantconvert//variantconvert convert -i 20230526_AnnotSV/PosCon2.annotsv.tsv -o 20230526_AnnotSV/PosCon2.ann.vcf.tsv -fi annotsv -fo vcf -c /usr/local/share/python3/variantconvert//configs/GRCh38/annotsv3_from_vcf.json

2023-05-26 14:50:23 [INFO] running variantconvert 1.2.2
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/share/python3/variantconvert//variantconvert/__main__.py", line 226, in <module>
    main()
  File "/usr/local/share/python3/variantconvert//variantconvert/__main__.py", line 209, in main
    main_convert(args)
  File "/usr/local/share/python3/variantconvert//variantconvert/__main__.py", line 74, in main_convert
    converter.convert(args.inputFile, args.outputFile)
  File "/usr/local/share/python3/variantconvert//variantconvert/converters/vcf_from_annotsv.py", line 460, in convert
    self.sample_list = self._get_sample_list()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/python3/variantconvert//variantconvert/converters/vcf_from_annotsv.py", line 76, in _get_sample_list
    raise ValueError(
ValueError: 0      When using an AnnotSV file generated from a VC...
1      When using an AnnotSV file generated from a VC...
2      When using an AnnotSV file generated from a VC...
3      When using an AnnotSV file generated from a VC...
4      When using an AnnotSV file generated from a VC...
                             ...                        
143    When using an AnnotSV file generated from a VC...
144    When using an AnnotSV file generated from a VC...
145    When using an AnnotSV file generated from a VC...
146    When using an AnnotSV file generated from a VC...
147    When using an AnnotSV file generated from a VC...
Name: Samples_ID, Length: 148, dtype: object
```

After investigating the TSV file I noticed that the Samples_ID column was empty causing VariantConvert to fail. 

My AnnotSV command is:
```
AnnotSV \
    -annotationsDir AnnotSV_annotations \
    -outputFile PosCon2.annotsv.tsv \
    -SVinputFile PosCon2.vcf.gz \
    -vcf 1
```

And the used VCF is:
[PosCon2.vcf.gz](https://github.com/lgmgeo/AnnotSV/files/11576534/PosCon2.vcf.gz)

What could be the problem for this? 

Thanks
-Nicolas

**Comment by lgmgeo** [comment]
Hi @nvnieuwk ,

Do you have any SV presents only in samples with GT = "./."?
Currently, AnnotSV does not report the sample_ID for that. And indeed,  empty Samples_ID column causes VariantConvert to fail.
I will add a fix asap for that (by reporting the sample_ID of such SV with missing alleles GT)

Sorry for the inconvenience,
Best,
Véronique

**Comment by nvnieuwk** [comment]
Hi @lgmgeo 
Thanks for the quick response!

The variants were all found using the Gridss variant caller which reports using the breakend notation. It somehow sets genotypes to `.` for all variants, I'll have to investigate that a bit further. 

Thanks you for proposing a fix this quickly! Nice working with you :)

Greets
-Nicolas

**Comment by lgmgeo** [comment]
Thanks for your nice words. Happy users make me happy ;o)
A fix for your problem is available on the AnnotSV_patch branch. Before releasing on the master branch, I have other features to explore this week.

**Comment by nvnieuwk** [comment]
Thank you! 😄

**Comment by nvnieuwk** [comment]
Thank you very much!

**Comment by nvnieuwk** [comment]
Hi this doesn't seem solved in version 3.3.6 😿 

I have following lines in the TSV created by AnnotSV:
```
AnnotSV_ID	SV_chrom	SV_start	SV_end	SV_length	SV_type	Samples_ID	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	PosCon1	Annotation_mode	CytoBand	Gene_name	Gene_count	Tx	Tx_start	Tx_end	Overlapped_tx_length	Overlapped_CDS_length	Overlapped_CDS_percent	Frameshift	Exon_count	Location	Location2	Dist_nearest_SS	Nearest_SS_type	Intersect_start	Intersect_end	RE_gene	P_gain_phen	P_gain_hpo	P_gain_source	P_gain_coord	P_loss_phen	P_loss_hpo	P_loss_source	P_loss_coord	P_ins_phen	P_ins_hpo	P_ins_source	P_ins_coord	po_P_gain_phen	po_P_gain_hpo	po_P_gain_source	po_P_gain_coord	po_P_gain_percent	po_P_loss_phen	po_P_loss_hpo	po_P_loss_source	po_P_loss_coord	po_P_loss_percent	P_snvindel_nb	P_snvindel_phen	B_gain_source	B_gain_coord	B_gain_AFmax	B_loss_source	B_loss_coord	B_loss_AFmax	B_ins_source	B_ins_coord	B_ins_AFmax	B_inv_source	B_inv_coord	B_inv_AFmax	po_B_gain_allG_source	po_B_gain_allG_coord	po_B_gain_someG_source	po_B_gain_someG_coord	po_B_loss_allG_source	po_B_loss_allG_coord	po_B_loss_someG_source	po_B_loss_someG_coord	TAD_coordinate	ENCODE_experiment	GC_content_left	GC_content_right	Repeat_coord_left	Repeat_type_left	Repeat_coord_right	Repeat_type_right	Gap_left	Gap_right	SegDup_left	SegDup_right	ENCODE_blacklist_left	ENCODE_blacklist_characteristics_left	ENCODE_blacklist_right	ENCODE_blacklist_characteristics_right	ACMG	HI	TS	DDD_HI_percent	ExAC_delZ	ExAC_dupZ	ExAC_cnvZ	ExAC_synZ	ExAC_misZ	GenCC_disease	GenCC_moi	GenCC_classification	GenCC_pmid	OMIM_ID	OMIM_phenotype	OMIM_inheritance	OMIM_morbid	OMIM_morbid_candidate	LOEUF_bin	GnomAD_pLI	ExAC_pLI	AnnotSV_ranking_score	AnnotSV_ranking_criteria	ACMG_class
16_1076979_1078894_INV_1	16	1076979	1078894	1131	INV		0_delly_INV00000001	T	<INV>	58	LowQual	CIEND=-392,392;CIPOS=-392,392;END=1078502;PE=2;MAPQ=29;CT=5to5;IMPRECISE;SVTYPE=INV;SVMETHOD=JASMINE;SVLEN=1131;STARTVARIANCE=0.000000;ENDVARIANCE=0.000000;AVG_LEN=1131.000000;AVG_START=1077371.000000;AVG_END=1078502.000000;VARCALLS=1;ALLVARS_EXT=(delly_INV00000001);SUPP_VEC_EXT=10;IDLIST_EXT=delly_INV00000001;SUPP_EXT=1;SUPP_VEC=10;SUPP=1;IDLIST=delly_INV00000001;INTRASAMPLE_IDLIST=delly_INV00000001	GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV	0/0:0,-0.521621,-107.701:6:LowQual:40:102:49:2:19:2:0:0	full	p13.3	SSTR5;SSTR5-AS1	2																														dbVar:nssv15158812;dbVar:nssv15148703;dbVar:nssv15147067;dbVar:nssv15148669;dbVar:nssv15147068;dbVar:nssv17649874;dbVar:nssv15152396;dbVar:nssv15150758;dbVar:nssv15149904;dbVar:nssv15154767;dbVar:nssv16254459;dbVar:nssv15149503;dbVar:nssv15150639;nssv15151292;dbVar:nssv15158813;dbVar:nssv15158224;dbVar:nssv15147425;dbVar:nssv15147959;dbVar:nssv15147069;dbVar:nssv15148094;dbVar:nssv15147790;dbVar:nssv8639650;dbVar:nssv15606077;dbVar:nssv15146792	16:11452-90228224;16:19194-90207973;16:23142-11296695;16:28802-9075591;16:29942-2560460;16:34486-5201012;16:35881-11115431;16:35881-19795599;16:35881-22430686;16:35881-3166550;16:35881-5199456;16:35881-9789272;16:35882-90088654;16:38166-90096867;16:38166-90208287;16:43733-13326806;16:46767-11525516;16:46767-3214623;16:46767-4247185;16:47134-5072973;16:52840-28316355;16:59981-4266796;16:666663-15743104	0.00;0.00;0.02;0.02;0.08;0.04;0.02;0.01;0.01;0.06;0.04;0.02;0.00;0.00;0.00;0.01;0.02;0.06;0.05;0.04;0.01;0.05;0.01			dbVar:nssv15173022;dbVar:nssv15147566;dbVar:nssv15145815;dbVar:nssv15147164;dbVar:nssv16208442;dbVar:nssv15772679;dbVar:nssv17969036;dbVar:nssv15155464;dbVar:nssv15155465;dbVar:nssv15776300;dbVar:nssv15146945;dbVar:nssv15148829;dbVar:nssv15148018;dbVar:nssv15145816;dbVar:nssv15138549;dbVar:nssv15147167;dbVar:nssv15771714;dbVar:nssv16214818	16:11452-1543644;16:22770-1461715;16:23142-1712523;16:23142-1773349;16:35881-1116355;16:35881-1418458;16:35881-1418827;16:35881-1448730;16:35881-1825693;16:35881-2003327;16:38166-1665453;16:46723-1867327;16:46767-1544014;16:46767-1997582;16:59981-1221651;16:105430-1499893;16:574056-2065655;16:574056-2098004	0.13;0.13;0.11;0.11;0.18;0.14;0.14;0.14;0.11;0.10;0.12;0.11;0.13;0.10;0.16;0.14;0.13;0.13			gnomAD-SV_v2.1_DUP_16_41049	16:1071345-1082316	0.0174													16:1071345-1082316 gnomAD-SV_v2.1_DUP_16_41049				16:1016254-1077714 dgv777e212			0.505	0.720	16:1076640-1077182	L1MEi														46.48				0.955487240053794	0.4030768552904										8	9.5544e-04	6.2334e-02			NA
16_1076979_1078894_INV_1	16	1076979	1078894	1131	INV		0_delly_INV00000001	T	<INV>	58	LowQual	CIEND=-392,392;CIPOS=-392,392;END=1078502;PE=2;MAPQ=29;CT=5to5;IMPRECISE;SVTYPE=INV;SVMETHOD=JASMINE;SVLEN=1131;STARTVARIANCE=0.000000;ENDVARIANCE=0.000000;AVG_LEN=1131.000000;AVG_START=1077371.000000;AVG_END=1078502.000000;VARCALLS=1;ALLVARS_EXT=(delly_INV00000001);SUPP_VEC_EXT=10;IDLIST_EXT=delly_INV00000001;SUPP_EXT=1;SUPP_VEC=10;SUPP=1;IDLIST=delly_INV00000001;INTRASAMPLE_IDLIST=delly_INV00000001	GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV	0/0:0,-0.521621,-107.701:6:LowQual:40:102:49:2:19:2:0:0	split	p13.3	SSTR5		NM_001172560	1072755	1081454	1916	26	1	yes	2	intron1-exon2	5'UTR-CDS	53	3'	1076978	1078894																										gnomAD-SV_v2.1_DUP_16_41049	16:1071345-1082316	0.0174																																					46.48				0.955487240053794	0.4030768552904										8	9.5544e-04	6.2334e-02			full=NA
16_1076979_1078894_INV_1	16	1076979	1078894	1131	INV		0_delly_INV00000001	T	<INV>	58	LowQual	CIEND=-392,392;CIPOS=-392,392;END=1078502;PE=2;MAPQ=29;CT=5to5;IMPRECISE;SVTYPE=INV;SVMETHOD=JASMINE;SVLEN=1131;STARTVARIANCE=0.000000;ENDVARIANCE=0.000000;AVG_LEN=1131.000000;AVG_START=1077371.000000;AVG_END=1078502.000000;VARCALLS=1;ALLVARS_EXT=(delly_INV00000001);SUPP_VEC_EXT=10;IDLIST_EXT=delly_INV00000001;SUPP_EXT=1;SUPP_VEC=10;SUPP=1;IDLIST=delly_INV00000001;INTRASAMPLE_IDLIST=delly_INV00000001	GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV	0/0:0,-0.521621,-107.701:6:LowQual:40:102:49:2:19:2:0:0	split	p13.3	SSTR5-AS1		NR_027242	1064080	1078731	1753	0	0	no	4	txStart-intron2	UTR	645	5'	1076978	1078731																										gnomAD-SV_v2.1_DUP_16_41049	16:1071345-1082316	0.0174																																																									full=NA
```

which corresponds to the only variant with a `0/0` genotype in the VCF file:
```
chr16	1077371	0_delly_INV00000001	T	<INV>	58	LowQual	CIEND=-392,392;CIPOS=-392,392;END=1078502;PE=2;MAPQ=29;CT=5to5;IMPRECISE;SVTYPE=INV;SVMETHOD=JASMINE;SVLEN=1131;STARTVARIANCE=0.000000;ENDVARIANCE=0.000000;AVG_LEN=1131.000000;AVG_START=1077371.000000;AVG_END=1078502.000000;VARCALLS=1;ALLVARS_EXT=(delly_INV00000001);SUPP_VEC_EXT=10;IDLIST_EXT=delly_INV00000001;SUPP_EXT=1;SUPP_VEC=10;SUPP=1;IDLIST=delly_INV00000001;INTRASAMPLE_IDLIST=delly_INV00000001	GT:GL:GQ:FT:RCL:RC:RCR:RDCN:DR:DV:RR:RV	0/0:0,-0.521621,-107.701:6:LowQual:40:102:49:2:19:2:0:0
```

Used command:
```
AnnotSV \
    -annotationsDir AnnotSV_annotations \
    -outputFile PosCon1.annot.tsv \
    -SVinputFile PosCon1.vcf.gz \
    -vcf 1 -SVminSize 20
```

Thanks in advance!
-Nicolas

**Comment by lgmgeo** [comment]
In the TSV created by AnnotSV, you have 3 lines corresponding to a single SV:
- 1 full line
- 2 split lines
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/562b8b7c-6d16-4c04-9fb7-9ca52b25049a)

In each line, the "Samples_ID" column is empty (which is normal because the GT is "0/0").
So everything looks good to me.

Why did you write that your bug doesn't seem to be fixed in 3.3.6, still a bug with variantconvert?

**Comment by nvnieuwk** [comment]
> In the TSV created by AnnotSV, you have 3 lines corresponding to a single SV:
> 
>     * 1 full line
> 
>     * 2 split lines
>       ![image](https://user-images.githubusercontent.com/49909073/243362847-562b8b7c-6d16-4c04-9fb7-9ca52b25049a.png)
> 
> 
> In each line, the "Samples_ID" column is empty (which is normal because the GT is "0/0"). So everything looks good to me.
> 
> Why did you write that your bug doesn't seem to be fixed in 3.3.6, still a bug with variantconvert?

Yes I'm sorry for being unclear what my issue was. The missing sample IDs still result in an error for variantconvert (the same error as before):

```
python3 /usr/local/share/python3/variantconvert//variantconvert convert -i 20230605_AnnotSV/PosCon1.annot.tsv -o 20230605_AnnotSV/PosCon1.annot.vcf -fi annotsv -fo vcf -c /usr/local/share/python3/variantconvert//configs/GRCh38/annotsv3_from_vcf.json

2023-06-05 14:10:39 [INFO] running variantconvert 1.2.2
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/share/python3/variantconvert//variantconvert/__main__.py", line 226, in <module>
    main()
  File "/usr/local/share/python3/variantconvert//variantconvert/__main__.py", line 209, in main
    main_convert(args)
  File "/usr/local/share/python3/variantconvert//variantconvert/__main__.py", line 74, in main_convert
    converter.convert(args.inputFile, args.outputFile)
  File "/usr/local/share/python3/variantconvert//variantconvert/converters/vcf_from_annotsv.py", line 460, in convert
    self.sample_list = self._get_sample_list()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/python3/variantconvert//variantconvert/converters/vcf_from_annotsv.py", line 76, in _get_sample_list
    raise ValueError(
ValueError: 0      When using an AnnotSV file generated from a VC...
1      When using an AnnotSV file generated from a VC...
2      When using an AnnotSV file generated from a VC...
3      When using an AnnotSV file generated from a VC...
4      When using an AnnotSV file generated from a VC...
                             ...                        
132    When using an AnnotSV file generated from a VC...
133    When using an AnnotSV file generated from a VC...
134    When using an AnnotSV file generated from a VC...
135    When using an AnnotSV file generated from a VC...
136    When using an AnnotSV file generated from a VC...
Name: Samples_ID, Length: 137, dtype: object
```

**Comment by lgmgeo** [comment]
OK, got it.

Currently, AnnotSV does not annotate SV from a VCF input file:
o If the variant is an indel (variant length < SVminSize)
o If the SV is not well formatted
o If the “END” of the SV is not defined
o In case of reciprocal breakend (square-bracketed notation, see below)

Regarding on your bug, the question is:
Should AnnotSV report/annotate SV absents from all the samples (GT=0/0 in each sample) or not?
Currently, my feeling is to answer "yes" because AnnotSV is an annotator. As a result, the "Samples_ID" output column may be empty. And so variantconvert results in an error.

2 choices:
- I may consider removing these SV (with only "0/0" GT) from the AnnotSV output
- we can request a patch from the developpers of variantconvert 

Another possibility would be to ask users to remove SV absents from all the samples in their VCF input file.

Can you share your feelings on this?

**Comment by nvnieuwk** [comment]
Thank you for the thorough answer! I think it would be best indeed to be able to annotate all variants. A patch from the variantconvert developers seems to be the most ideal solution in this case IMO. 

I'll filter out these variants for now before using AnnotSV until this patch has been made.

**Comment by lgmgeo** [comment]
I contacted @SamuelNicaise, the developpers of variantconvert.
He will add a patch to handle empty `Samples_ID` column in TSV AnnotSV output (in case input VCF is provided with SV without any associated sample in the input VCF).

**Comment by nvnieuwk** [comment]
Awesome! Thank you!

**Comment by nvnieuwk** [comment]
Awesome thank you! And have fun on your holiday!

**Comment by lgmgeo** [comment]
[AnnotSV 3.4.1](https://github.com/lgmgeo/AnnotSV) was posted with an updated version of variantconvert (v2.0.1).
Can you confirm that this fixes your bug?

**Comment by nvnieuwk** [comment]
I'll give it a go in a couple of days :eyes:

**Comment by lgmgeo** [comment]
Hi, any news?

**Comment by nvnieuwk** [comment]
Hi no I haven't been able to get the conda recipe to work yet :/

**Comment by nvnieuwk** [comment]
Hi I've finally managed to get it working and using the same command and file posted in the first message of this issue results in the error in this file: 
[test.variantconvert.log](https://github.com/lgmgeo/AnnotSV/files/15486240/test.variantconvert.log)

**Comment by lgmgeo** [comment]
[@SamuelNicaise](https://github.com/SamuelNicaise): Can you have a look at it?
![image](https://github.com/lgmgeo/AnnotSV/assets/49909073/3e67be24-c734-45a9-beb0-f076b900bf83)

**Comment by SamuelNicaise** [comment]
Hi, 

This warning is because something variantconvert is doing has been deprecated in pandas 2.1. 

I will update variantconvert to adapt to this change as it will eventually result into an error in future versions of pandas. 

For now you can safely ignore it.

If you wish to mute the warning, you can change pandas to a previous version like this: 
`pip install --force-reinstall 'pandas<2.1'`

Best,

**Comment by nvnieuwk** [comment]
Thank you!

**Comment by lgmgeo** [comment]
So everything is working now correctly?
No more Sample_ID bug?

**Comment by nvnieuwk** [comment]
Indeed! It fully works now except for that warning, but that's not a breaking issue right now. Thanks for the help!
