### ISSUE TITLE
AnnotSV: raise ValueError( ValueError: Each variant is assumed to only have one single line of 'full' annotation

### ISSUE THREAD

**Issue by cdbope** [lgmgeo/AnnotSV#262]
Any advice on how to handle this error when trying to generate vcf output using AnnotSV. 
`python3 /AnnotSV/share/python3/variantconvert//src/variantconvert convert -i /data/annotated_variants.tsv -o /data/annotated_variants.vcf -c /AnnotSV/share/python3/variantconvert//src/variantconvert/configs/GRCh38/annotsv3_from_vcf.combined.local.json

2024-10-17 12:15:43 [INFO] running variantconvert 2.0.1
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/AnnotSV/share/python3/variantconvert//src/variantconvert/__main__.py", line 242, in <module>
    main()
  File "/AnnotSV/share/python3/variantconvert//src/variantconvert/__main__.py", line 222, in main
    main_convert(args)
  File "/AnnotSV/share/python3/variantconvert//src/variantconvert/__main__.py", line 77, in main_convert
    converter.convert(args.inputFile, args.outputFile)
  File "/AnnotSV/share/python3/variantconvert/src/variantconvert/converters/vcf_from_annotsv.py", line 402, in convert
    info_input_dic = self._build_info_dic()
  File "/AnnotSV/share/python3/variantconvert/src/variantconvert/converters/vcf_from_annotsv.py", line 205, in _build_info_dic
    merged_annots = merge_full_and_split(self.config, self.sample_list, df_variant)
  File "/AnnotSV/share/python3/variantconvert/src/variantconvert/converters/vcf_from_annotsv_tools.py", line 95, in merge_full_and_split
    raise ValueError(
ValueError: Each variant is assumed to only have one single line of 'full' annotation
`
Command: 
singularity exec annotsv_images.sif   AnnotSV  -SVinputFile filtered_output.vcf -annotationsDir /annotations/   -vcf 1    -outputFile annotated_variants.tsv  
`

**Comment by lgmgeo** [comment]
> ValueError: Each variant is assumed to only have one single line of 'full' annotation



It looks like you have the same SV described on 2 lines in your input file.
